version: '3.3'
services:
  app:
    env_file: .env
    build:
      context: megaphone/app
      dockerfile: Dockerfile
    ports: ['3000:3000']
    volumes:
      - ./megaphone/app:/app
      - /app/node_modules

  twitter:
    env_file: .env
    build:
      context: megaphone/scheduler
      dockerfile: Dockerfile
    image: scheduler
    ports: ['3001:3000']
    command: ["npm", "run", "twitter"]
    volumes:
      - ./megaphone/scheduler:/app
      - /app/node_modules

  facebook:
    env_file: .env
    build:
      context: megaphone/scheduler
      dockerfile: Dockerfile
    ports: ['3002:3000']
    command: ["npm", "run", "facebook"]
    volumes:
      - ./megaphone/scheduler:/app
      - /app/node_modules

  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
