version: '3.3'
services:
  web:
    env_file: .env
    build: .
    ports:
      - '3000:3000'

  cat:
    env_file: .env
    build:
      context: services/twitter/
      dockerfile: Dockerfile
    ports:
      - '3001:3000'

  dog:
    env_file: .env
    build:
      context: services/facebook/
      dockerfile: Dockerfile
    ports:
      - '3002:3000'
