version: '3.3'
services:
  app:
    env_file: .env
    build:
      context: megaphone/app
      dockerfile: Dockerfile
    image: megaphone/app
    ports: ['3000:3000']
    command: ["npm", "run", "dev"]
    volumes:
      - ./megaphone/app:/app
      - /app/node_modules

  twitter:
    env_file: .env
    build:
      context: megaphone/scheduler
      dockerfile: Dockerfile
    image: megaphone/scheduler
    ports: ['3001:3000']
    command: ["npm", "run", "dev", "twitter"]
    volumes:
      - ./megaphone/scheduler:/app
      - /app/node_modules

  facebook:
    env_file: .env
    build:
      context: megaphone/scheduler
      dockerfile: Dockerfile
    image: megaphone/scheduler
    ports: ['3002:3000']
    command: ["npm", "run", "dev", "facebook"]
    volumes:
      - ./megaphone/scheduler:/app
      - /app/node_modules

  linkedin:
    env_file: .env
    build:
      context: megaphone/scheduler
      dockerfile: Dockerfile
    image: megaphone/scheduler
    ports: ['3003:3000']
    command: ["npm", "run", "dev", "linkedin"]
    volumes:
      - ./megaphone/scheduler:/app
      - /app/node_modules

  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
