version: '3.3'
services:
  web:
    env_file: .env
    build: .
    ports:
      - '3000:3000'

  twitter:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile.publisher.twitter
    ports:
      - '3001:3000'

  facebook:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile.publisher.facebook
    ports:
      - '3002:3000'
