version: '3'

services:
  web:
    env_file:
      - .env
    build: .
    image: megaphonely/web
    command: ./scripts/run_web.sh
    ports:
      - "8000:8000"

  rabbit:
    hostname: rabbit
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672:5672"  # we forward this port because it's useful for debugging
      - "15672:15672"  # here, we can access rabbitmq management plugin

  worker:
    env_file:
      - .env
    build: .
    image: megaphonely/worker
    command: ./scripts/run_worker.sh
    links:
      - rabbit
    depends_on:
      - rabbit