branch-defaults:
  master:
    environment: megaphone-stg
    group_suffix: null
global:
  application_name: megaphone
  branch: null
  default_ec2_keyname: null
  default_platform: Python 2.7
  default_region: eu-west-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
