branch-defaults:
  master:
    environment: megaphone-stg
environment-defaults:
  megaphone-stg:
    branch: null
    repository: null
global:
  application_name: megaphone
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:eu-west-1::platform/Python 2.7 running
    on 64bit Amazon Linux/2.5.2
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
