branch-defaults:
  master:
    environment: megaphonely2-dev
    group_suffix: null
global:
  application_name: megaphonely2
  branch: null
  default_ec2_keyname: null
  default_platform: Docker 1.12.6
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
