version: 2
general:
  branches:
    only:
      - master
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
        environment:
          SECRET_KEY: test
          DEBUG: True
          TWITTER_CONSUMER_KEY: test
          TWITTER_CONSUMER_SECRET: test
          AWS_S3_REGION_NAME: test
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
          AWS_S3_CUSTOM_DOMAIN: test
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python manage.py test
      - run:
          name: deploy application
          command: |
            . venv/bin/activate
            python manage.py collectstatic
            eb deploy --debug
      - store_artifacts:
          path: test-reports
          destination: test-reports