version: '2'
services:
  facebook:
    env_file: .env.prod
    mem_limit: 134217728
    image: jkrclaro/scheduler
    command: ["npm", "run", "facebook"]
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "eu-west-1"
        awslogs-group: "scheduler-log-group"
  twitter:
    env_file: .env.prod
    mem_limit: 134217728
    image: jkrclaro/scheduler
    command: ["npm", "run", "twitter"]
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "eu-west-1"
        awslogs-group: "scheduler-log-group"
